version: "3"

services:
  local-redis:
    image: redis
    container_name:
      rails-redis

  local-rails:
    image: "nginx"
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - local-redis
    env_file:
      - env_file.env
    container_name:
      rails-rails
    command:
      bundle exec rails s -p 80 -b '0.0.0.0'
